version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms750m -Xmx750m
    ports:
      - 9200:9200
      - 9300:9300
  fluentd:
    build: ./fluentd
    ports:
      - 24224:24224
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  demo-app:
    build: ./demo-app
    ports:
      - 8090:8090
    depends_on:
      - elasticsearch
    logging:
      # Send all logs from this docker container to our fluentd container for parsing.
      driver: "fluentd"
      options:
       tag: "spring-boot.demoapp"
       fluentd-address: "192.168.99.110:24224"
